# Generated by Django 5.0.1 on 2024-01-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='depts',
            new_name='deptartment',
        ),
    ]
