# Generated by Django 5.0.1 on 2024-01-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_rename_depts_hospital_deptartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='deptartment',
            new_name='deptartments',
        ),
    ]
