# Generated by Django 5.0.1 on 2024-01-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_rename_deptartment_hospital_deptartments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='deptartments',
            new_name='departments',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hname',
            new_name='name',
        ),
    ]
