# Generated by Django 5.0.1 on 2024-01-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_rename_dname_department_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('name', 'address')},
        ),
    ]
