# Generated by Django 5.0.1 on 2024-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_hospital_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
