# Generated by Django 5.0.1 on 2024-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('symptoms', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('outpatient', 'outpatient'), ('admitted', 'admitted'), ('discharged', 'discharged')], max_length=20)),
            ],
        ),
    ]
