# Generated by Django 5.0.1 on 2024-01-16 07:44

import django.core.validators
import django.db.models.deletion
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField(validators=[patients.models.Patient.validate_age])),
                ('mobilenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='10 digit number', regex='^[1-9]\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('primary check', 'primary check'), ('consultation', 'consultation'), ('admitted', 'admitted'), ('discharged', 'discharged')], default='consultation', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.department')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
