# Generated by Django 5.0.1 on 2024-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_delete_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobilenumber',
            field=models.DecimalField(decimal_places=0, default=9818198181, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('admitted', 'admitted'), ('discharged', 'discharged')], default='waiting', max_length=20),
        ),
    ]
