# Generated by Django 5.0.1 on 2024-01-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0003_patient_mobilenumber_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='department_id',
            field=models.ForeignKey(choices=[('OPD', 1)], default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.department'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.ForeignKey(choices=[('Appollo koramangala', 1), ('Sagar Apollo', 2)], default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
    ]
