# Generated by Django 5.0.1 on 2024-01-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_patient_date_patient_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
            preserve_default=False,
        ),
    ]
