# Generated by Django 5.0.1 on 2024-01-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pname',
            new_name='name',
        ),
    ]
