# Generated by Django 5.0.1 on 2024-01-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_docname_doctor_name'),
        ('hospitals', '0004_rename_dname_department_name_and_more'),
        ('patients', '0011_alter_patient_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', limit_choices_to={'hospital_id': models.F('hospital')}, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
