# Generated by Django 5.0.1 on 2024-01-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_docname_doctor_name'),
        ('patients', '0012_patient_hospital_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', limit_choices_to={'hospital_id': models.F('hospital_ID')}, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
