# Generated by Django 5.0.1 on 2024-01-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_docname_doctor_name'),
        ('patients', '0015_patient_department_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', limit_choices_to={'department_id': models.F('department_id'), 'hospital_id': models.F('hospital_id')}, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
