# Generated by Django 5.0.1 on 2024-01-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_docname_doctor_name'),
        ('hospitals', '0004_rename_dname_department_name_and_more'),
        ('patients', '0017_alter_patient_department_alter_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
    ]
