# Generated by Django 5.0.1 on 2024-01-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_patient_department_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-visit_date']},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date',
            new_name='visit_date',
        ),
    ]
