# Generated by Django 5.0.1 on 2024-01-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-visit_date']},
        ),
    ]
