# Generated by Django 5.0.1 on 2024-01-15 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_remove_patient_symptoms_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobilenumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='10 digit number', regex='^[1-9]\\d{9}$')]),
        ),
    ]
