# Generated by Django 5.0.1 on 2024-01-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_department_remove_doctor_hospital'),
        ('hospitals', '0002_rename_depts_hospital_deptartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
            preserve_default=False,
        ),
    ]
