# Generated by Django 5.0.1 on 2024-01-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_department_doctor_hospital'),
        ('hospitals', '0003_rename_deptartment_hospital_deptartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(db_column='hospital_id', on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
    ]
