# Generated by Django 5.0.1 on 2024-01-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_department_alter_doctor_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='docname',
            new_name='name',
        ),
    ]
