# Generated by Django 5.0.1 on 2024-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_docname_doctor_name'),
        ('hospitals', '0004_rename_dname_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(db_column='hospital_id', limit_choices_to={'departments': models.F('department')}, to='hospitals.hospital'),
        ),
    ]
