# Generated by Django 5.0.1 on 2024-01-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital',
            new_name='hospitals',
        ),
    ]
