# Generated by Django 5.0.1 on 2024-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctor_hospitals'),
        ('hospitals', '0007_alter_hospital_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(db_column='hospital_id', db_table='doctors_doctor_hospital', to='hospitals.hospital'),
        ),
    ]
